#ifndef ACTION_H
#define ACTION_H

enum action {
  ACTION_NONE,
  ACTION_QUIT,
 
  ACTION_VIEWPORT_LEFT,
  ACTION_VIEWPORT_RIGHT,
  ACTION_VIEWPORT_UP,
  ACTION_VIEWPORT_DOWN,
  ACTION_VIEWPORT_CENTER,
  
  ACTION_WINDOW_MOVE,
  ACTION_WINDOW_RESIZE,
  ACTION_WINDOW_CLOSE,
  ACTION_WINDOW_FULLSCREEN_TOGGLE,
  ACTION_WINDOW_STICKY_TOGGLE,
  ACTION_WINDOW_JUMP,

  ACTION_FOCUS_NEXT,
  ACTION_FOCUS_PREVIOUS,
  ACTION_FOCUS_WINDOW,

  ACTION_ZOOM_IN,
  ACTION_ZOOM_OUT,
  ACTION_ZOOM_RESET,

};

void
action_execute(enum action action);

#endif
