#ifndef ACTION_H
#define ACTION_H

enum action {
  ACTION_NONE,
  ACTION_CANVAS_PAN,
  ACTION_CANVAS_ZOOM,

  ACTION_VIEWPORT_LEFT,
  ACTION_VIEWPORT_RIGHT,
  ACTION_VIEWPORT_UP,
  ACTION_VIEWPORT_DOWN,
  
  ACTION_MOVE_WINDOW,
  ACTION_RESIZE_WINDOW,

  ACTION_FOCUS_WINDOW,
  ACTION_CLOSE_WINDOW,
  ACTION_FULLSCREEN_WINDOW,
  ACTION_STICKY_WINDOW,
  ACTION_JUMP_WINDOW,

  ACTION_FOCUS_NEXT,
  ACTION_FOCUS_PREVIOUS,

  ACTION_SPAWN,
  ACTION_QUIT,

};

void
action_execute(enum action action);

#endif
