#ifndef ACTION_H
#define ACTION_H

#include <stdbool.h>

enum action {
  //CANVAS COMPOSITOR ACTION
  ACTION_NONE,
  ACTION_QUIT,
 
  //CANVAS NAVIGATION ACTION
  ACTION_VIEWPORT_LEFT,
  ACTION_VIEWPORT_RIGHT,
  ACTION_VIEWPORT_UP,
  ACTION_VIEWPORT_DOWN,
  ACTION_VIEWPORT_CENTER,
  ACTION_VIEWPORT_NAVIGATE,

  
  //CANVAS WINDOW ACTION
  ACTION_WINDOW_MOVE,
  ACTION_WINDOW_RESIZE,
  ACTION_WINDOW_CLOSE,
  ACTION_WINDOW_FULLSCREEN_TOGGLE,
  ACTION_WINDOW_STICKY_TOGGLE,
  ACTION_WINDOW_JUMP,

  //CANVAS FOCUS ACTION
  ACTION_FOCUS_NEXT,
  ACTION_FOCUS_PREVIOUS,

  //CANVAS ZOOM ACTION
  ACTION_ZOOM_IN,
  ACTION_ZOOM_OUT,
  ACTION_ZOOM_RESET,

};

void
action_execute(enum action action, bool held);

#endif
